# Generated by Django 3.2.8 on 2021-11-14 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('verification_status', models.BooleanField(default=False)),
                ('rewarded_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=10)),
                ('bio_char', models.CharField(max_length=100)),
                ('interests', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('website', models.CharField(max_length=12)),
                ('major', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spapp.major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_service', to='spapp.activities')),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='validator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spapp.validator'),
        ),
        migrations.CreateModel(
            name='AcademicRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=15)),
                ('gpa', models.FloatField(max_length=3)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_recognition', to='spapp.activities')),
                ('activity_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spapp.activities')),
            ],
        ),
    ]
