# Generated by Django 3.2.8 on 2021-11-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0002_auto_20211114_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
