# Generated by Django 3.2.8 on 2021-11-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0005_auto_20211121_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicrecognition',
            name='activity_type',
        ),
    ]
