# Generated by Django 4.0.2 on 2022-02-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0007_remove_activities_user_activities_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resonsibility', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='spapp.activities')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
