# Generated by Django 4.0.2 on 2022-02-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0009_job_validator_verified_alter_activities_validator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountremovalrequest',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accountremovalrequest',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_removal_request', to='spapp.student'),
        ),
    ]
