# Generated by Django 4.0.2 on 2022-02-23 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spapp', '0010_alter_accountremovalrequest_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
