# Generated by Django 4.0.2 on 2022-02-23 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spapp', '0011_validator_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecognition',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_recognition', to='spapp.activities'),
        ),
        migrations.AlterField(
            model_name='accountremovalrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_removal_request', to='spapp.student'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spapp.student'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='validator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spapp.validator'),
        ),
        migrations.AlterField(
            model_name='communityservice',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_service', to='spapp.activities'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='spapp.activities'),
        ),
        migrations.AlterField(
            model_name='project',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='spapp.activities'),
        ),
        migrations.AlterField(
            model_name='research',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='spapp.activities'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spapp.major'),
        ),
        migrations.AlterField(
            model_name='validator',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
