# Generated by Django 4.0.2 on 2022-02-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0012_alter_academicrecognition_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountremovalrequest',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_removal_request', to='spapp.student'),
        ),
    ]
