# Generated by Django 4.0.2 on 2022-02-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0013_alter_accountremovalrequest_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecognition',
            name='semester',
            field=models.CharField(choices=[('first_semester', 'First Semester'), ('second_semester', 'Second Semester')], max_length=30),
        ),
    ]
