# Generated by Django 4.0.2 on 2022-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0014_alter_academicrecognition_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
