# Generated by Django 4.0.2 on 2022-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0015_alter_activities_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
